### ISSUE TITLE
About the scale

### ISSUE THREAD

**Issue by dz-paji** [lzjluzijie/gobench#2]
![image](https://user-images.githubusercontent.com/19299425/39243680-e959881e-48c0-11e8-9fd8-b82545d7b0bd.png)
The scale shows in the picture is a bit difficult to understand.... Maybe can correct them to MB(MB/s) ?

**Comment by lzjluzijie** [comment]
The disk benchmark is suck. I will rewrite all of them.

**Comment by lzjluzijie** [comment]
done
